In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

In [2]:
#pkg = mp.jupyter.open_package()
pkg = mp.jupyter.open_source_package()
pkg

# Special economic zones
`worldbank.org-sez-1.1.1` Last Update: 2021-07-09T23:04:50

_Information on special economic zones have been individually collected and researched in a study focusing on the governance of SEZ. This is just a subset (586) of the extant global SEZs, which have been estimated at 3500-4000._


## Documentation Links

* [Dataset webpage](https://datacatalog.worldbank.org/dataset/special-economic-zones-sez)
* [Dataset viewer web application](http://devseed.com/sez-viewer/#/BGD6)



## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [sez](https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/1189121/ciip_sez_ntl_2017.geojson)**. Special Economic Zones

In [3]:
sez = pkg.resource('sez').dataframe()
sez.head()

,id,unique_id,Check,latitude,longitude,country_code,country_type_combo,region,country,zone_type,...,populous_citydist,city_1m,city_1mdist,city_500k,city_500kdist,500kcity_range,city_300k,city_300kdist,Note,geometry
0,0,URY12,URY,-33.887443,-58.416899,URY,URYFree Zone,LAC,Uruguay,Free Zone,...,265,Montevideo,265,Montevideo,265,50 to 299 km,Montevideo,265,None,POINT (-58.416899 -33.887443)
1,1,URY2,URY,-34.470636,-57.831424,URY,URYFree Zone,LAC,Uruguay,Free Zone,...,182,Montevideo,182,Montevideo,182,50 to 299 km,Montevideo,182,None,POINT (-57.831424 -34.470636)
2,2,COL2,COL,10.960451,-74.762902,COL,COLFree Industrial Zone,LAC,Colombia,Free Industrial Zone,...,1013,Barranquilla,6,Barranquilla,6,Less than 50 km,Barranquilla,6,None,POINT (-74.762902 10.960451)
3,3,GUY3,GUY,6.791794,-58.167016,GUY,GUYIndustrial Estate,LAC,Guyana,Industrial Estate,...,4,No city in country with population greater tha...,0,No city in country with population greater tha...,0,Less than 50 km,No city in country with population greater tha...,0,The Government has noted that existing industr...,POINT (-58.167016 6.791794)
4,4,IND186,IND,23.034146,70.127156,IND,INDSpecial Economic Zone,SA,India,Special Economic Zone,...,830,Rajkot,191,Morbi,191,50 to 299 km,Morbi,191,None,POINT (70.127156 23.034146)

In [4]:
sez.country.value_counts()

Vietnam               94
Korea                 86
Turkey                53
Philippines           47
China                 35
Indonesia             27
Thailand              26
Colombia              22
Dominican Republic    14
Russia                13
Sri Lanka             13
Bangladesh            11
Uruguay               10
Ethiopia               9
Costa Rica             9
India                  9
Honduras               8
Egypt                  8
Nigeria                8
Argentina              7
Cameroon               6
Tanzania               6
Bolivia                6
Mozambique             4
Pakistan               4
Malaysia               4
Jordan                 4
Haiti                  3
Chile                  3
Jamaica                3
Guyana                 3
Belize                 2
South Africa           2
Eritrea                2
Lesotho                2
Senegal                2
Guatemala              2
Djibouti               2
Ghana                  1
Sudan                  1
Cote D'Ivoire          1
Kenya                  1
Gambia                 1
Fiji                   1
Benin                  1
Rwanda                 1
Angola                 1
Republic of Congo      1
Uganda                 1
Madagascar             1
Zimbabwe               1
Burundi                1
Botswana               1
Name: country, dtype: int64